// Türkçe Kitap Veri Tabanı'ndaki (Kitapyurdu kaynaklı, ~67 bin kitap) ham
// "kategori" alanı 130 farklı, hiyerarşik ve dağınık bir etiket seti
// (ör. "Edebiyat > Roman (Yerli)", "Edebiyat > Şiir (Çeviri)"). Bunu
// STORYTEL_KATEGORILERI'nin (bkz. storytelKategorileri.js) id/ad/renk
// dilini birebir yansıtacak şekilde, küçük ve sabit bir üst kategori
// setinde topluyoruz.
//
// Bu bir Firestore alanı DEĞİL — statik veri setinin (public/veri/
// turkce-kitaplar.json) ham kategori dizesinden türetiliyor, bkz.
// hamKategoridenUstKategoriGetir() ve turkceKitapVeriTabani.js'teki
// ustKategorideKitaplariGetir() / tumUstKategorileriGetir().
export const KITAP_UST_KATEGORILERI = [
  { id: 'roman', ad: 'Roman', renk: '#f5c95c' },
  { id: 'siir-drama', ad: 'Şiir & Drama', renk: '#e8622e' },
  { id: 'oyku', ad: 'Öykü', renk: '#4fae82' },
  { id: 'deneme-inceleme', ad: 'Deneme & İnceleme', renk: '#f0a0c4' },
  { id: 'ani-biyografi', ad: 'Anı & Biyografi', renk: '#6badf0' },
  { id: 'bilim-kurgu-fantastik', ad: 'Bilim Kurgu & Fantastik', renk: '#6badf0' },
  { id: 'polisiye-gerilim', ad: 'Polisiye & Gerilim', renk: '#4fae82' },
  { id: 'klasikler', ad: 'Klasikler', renk: '#e8622e' },
  { id: 'cizgi-roman', ad: 'Çizgi Roman', renk: '#f5c95c' },
  { id: 'mizah-soylesi', ad: 'Mizah & Söyleşi', renk: '#f0a0c4' },
  { id: 'cocuk-genclik', ad: 'Çocuk & Gençlik', renk: '#f0a0c4' },
  { id: 'tarih', ad: 'Tarih', renk: '#4fae82' },
  { id: 'toplum-siyaset', ad: 'Toplum & Siyaset', renk: '#e8622e' },
  { id: 'kultur-sanat', ad: 'Kültür & Sanat', renk: '#6badf0' },
  { id: 'psikoloji-felsefe', ad: 'Psikoloji & Felsefe', renk: '#f5c95c' },
  { id: 'din-maneviyat', ad: 'Din & Maneviyat', renk: '#4fae82' },
  { id: 'dil-egitim', ad: 'Dil & Eğitim', renk: '#f5c95c' },
  { id: 'diger', ad: 'Diğer', renk: '#6badf0' },
]

// Ham kategori dizesi -> üst kategori id. 67.260 kayıttaki TÜM 130
// benzersiz ham değeri tek tek eşleştirdik (bkz. bu görüşmede yapılan
// analiz) — sayım tam 67.260'a denk geliyor, kayıp/çakışma yok.
const HAM_KATEGORI_ESLESTIRME = {
  'Din > Ateizm': 'din-maneviyat',
  'Din > Budizm': 'din-maneviyat',
  'Din > Dini Metinler': 'din-maneviyat',
  'Din > Diğer': 'din-maneviyat',
  'Din > Felsefe-Sosyoloji-Psikoloji': 'din-maneviyat',
  'Din > Tarih': 'din-maneviyat',
  'Diğer > Gençlik Kitapları > Edebiyat': 'cocuk-genclik',
  'Diğer > Gençlik Kitapları > Eğitici ve Kaynak Kitaplar': 'cocuk-genclik',
  'Diğer > Güzel-Özlü Sözler': 'mizah-soylesi',
  'Diğer > Söyleşi': 'mizah-soylesi',
  'Diğer Dildeki Yayınlar > Almanca': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Arapça': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Diğer': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Fransızca': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Korece': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Kürtçe': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Osmanlıca': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Rusça': 'dil-egitim',
  'Diğer Dildeki Yayınlar > Yunanca': 'dil-egitim',
  'Diğer Dildeki Yayınlar > İngilizce': 'dil-egitim',
  'Diğer Dildeki Yayınlar > İspanyolca': 'dil-egitim',
  'Diğer Dildeki Yayınlar > İtalyanca': 'dil-egitim',
  Edebiyat: 'diger',
  'Edebiyat > 100 Temel Eser': 'klasikler',
  'Edebiyat > Aforizma': 'mizah-soylesi',
  'Edebiyat > Anlatı': 'mizah-soylesi',
  'Edebiyat > Antoloji-Derleme': 'mizah-soylesi',
  'Edebiyat > Anı (Hatırat)': 'ani-biyografi',
  'Edebiyat > Armağan': 'mizah-soylesi',
  'Edebiyat > Belgesel Roman': 'roman',
  'Edebiyat > Bilimkurgu-Fantazya': 'bilim-kurgu-fantastik',
  'Edebiyat > Biyografi-Otobiyografi': 'ani-biyografi',
  'Edebiyat > Deneme (Yerli)': 'deneme-inceleme',
  'Edebiyat > Deneme (Çeviri)': 'deneme-inceleme',
  'Edebiyat > Destan': 'klasikler',
  'Edebiyat > Divan Edebiyatı': 'klasikler',
  'Edebiyat > Diğer': 'diger',
  'Edebiyat > Doğu Klasikleri': 'klasikler',
  'Edebiyat > Edebiyat Tarihi': 'deneme-inceleme',
  'Edebiyat > Edebiyat Yazıları': 'deneme-inceleme',
  'Edebiyat > Eleştiri': 'deneme-inceleme',
  'Edebiyat > Günlük': 'ani-biyografi',
  'Edebiyat > Halk Edebiyatı': 'klasikler',
  'Edebiyat > Hiciv-Mizah': 'mizah-soylesi',
  'Edebiyat > Hikaye (Yerli)': 'oyku',
  'Edebiyat > Hikaye (Çeviri)': 'oyku',
  'Edebiyat > Hitabet-Söyleşi': 'mizah-soylesi',
  'Edebiyat > Korku-Gerilim': 'polisiye-gerilim',
  'Edebiyat > Mektup': 'ani-biyografi',
  'Edebiyat > Polemik': 'deneme-inceleme',
  'Edebiyat > Polisiye': 'polisiye-gerilim',
  'Edebiyat > Roman (Yerli)': 'roman',
  'Edebiyat > Roman (Çeviri)': 'roman',
  'Edebiyat > Tarihi Roman': 'roman',
  'Edebiyat > Çizgi Roman': 'cizgi-roman',
  'Edebiyat > Çizgi Roman > Manga - Anime': 'cizgi-roman',
  'Edebiyat > İnceleme': 'deneme-inceleme',
  'Edebiyat > Şiir (Yerli)': 'siir-drama',
  'Edebiyat > Şiir (Çeviri)': 'siir-drama',
  'Eğitim > Dil Eğitimi': 'dil-egitim',
  'Eğitim > Eğitime Yardımcı Kitaplar': 'dil-egitim',
  'Eğlence-Mizah > Genel': 'mizah-soylesi',
  'Eğlence-Mizah > Çizgi Roman': 'cizgi-roman',
  'Felsefe-Düşünce > Diğer': 'psikoloji-felsefe',
  'Felsefe-Düşünce > Felsefe Metinleri': 'psikoloji-felsefe',
  'Felsefe-Düşünce > Filozoflar-Düşünürler': 'psikoloji-felsefe',
  'Kültür > Antropoloji': 'kultur-sanat',
  'Kültür > Etnoloji': 'kultur-sanat',
  'Kültür > Folklor': 'kultur-sanat',
  'Kültür > Genel': 'kultur-sanat',
  'Kültür > Kültür Tarihi': 'kultur-sanat',
  'Kültür > Kültür Yazıları': 'kultur-sanat',
  'Psikoloji > Bilim': 'psikoloji-felsefe',
  'Psikoloji > Biyografi': 'ani-biyografi',
  'Psikoloji > Genel': 'psikoloji-felsefe',
  'Psikoloji > Psikolojik Danışma': 'psikoloji-felsefe',
  'Psikoloji > Yaklaşımlar': 'psikoloji-felsefe',
  'Psikoloji > İnceleme': 'psikoloji-felsefe',
  'Sanat > Diğer': 'kultur-sanat',
  'Sanat > Resim > Resim Teknikleri': 'kultur-sanat',
  'Sinema-Tiyatro': 'siir-drama',
  'Sinema-Tiyatro > Oyun (Yerli)': 'siir-drama',
  'Siyaset > Araştırma-İnceleme': 'toplum-siyaset',
  'Siyaset > Biyografi-Otobiyografi': 'ani-biyografi',
  'Siyaset > Bölgeler-Ülkeler': 'toplum-siyaset',
  'Siyaset > Devlet': 'toplum-siyaset',
  'Siyaset > Diğer': 'toplum-siyaset',
  'Siyaset > Etnik Sorunlar': 'toplum-siyaset',
  'Siyaset > Güncel Sorunlar': 'toplum-siyaset',
  'Siyaset > Hatıralar': 'ani-biyografi',
  'Siyaset > Mustafa Kemal Atatürk': 'ani-biyografi',
  'Siyaset > Siyasal Düşünce': 'toplum-siyaset',
  'Siyaset > Siyasal Hareketler-Eylemler-Topluluklar': 'toplum-siyaset',
  'Siyaset > Siyasal Hayat (Türkiye)': 'toplum-siyaset',
  'Siyaset > Siyasal Sistemler': 'toplum-siyaset',
  'Siyaset > Siyasal Tarih': 'toplum-siyaset',
  'Siyaset > Siyasal Yazılar-Tezler': 'toplum-siyaset',
  'Siyaset > Siyasi Kurgu': 'toplum-siyaset',
  'Siyaset > Terör-Mafya': 'toplum-siyaset',
  Tarih: 'tarih',
  'Tarih > Araştırma-İnceleme': 'tarih',
  'Tarih > Belgeler': 'tarih',
  'Tarih > Bölgeler-Ülkeler': 'tarih',
  'Tarih > Diğer': 'tarih',
  'Tarih > Hatıralar': 'ani-biyografi',
  'Tarih > Kişiler': 'ani-biyografi',
  'Tarih > Kuram': 'tarih',
  'Tarih > Seyahatname': 'tarih',
  'Tarih > Siyasal Tarih': 'tarih',
  'Tarih > Sosyal Tarih': 'tarih',
  'Tarih > Türk-Osmanlı': 'tarih',
  'Tarih > Türkiye': 'tarih',
  'Tarih > Yerel Tarih': 'tarih',
  'Tarih > Çağlar-Dönemler': 'tarih',
  'Tarih > Önemli Olaylar': 'tarih',
  'Çocuk Kitapları': 'cocuk-genclik',
  'Çocuk Kitapları > 100 Temel Eser': 'klasikler',
  'Çocuk Kitapları > 12+ Yaş > Hikaye': 'oyku',
  'Çocuk Kitapları > 6-12 Yaş > Hikaye': 'oyku',
  'Çocuk Kitapları > Ana-Baba kitapları': 'cocuk-genclik',
  'Çocuk Kitapları > Diğer': 'cocuk-genclik',
  'Çocuk Kitapları > Hikaye': 'oyku',
  'Çocuk Kitapları > Kaynak Kitaplar > Genel': 'cocuk-genclik',
  'Çocuk Kitapları > Okul Öncesi': 'cocuk-genclik',
  'Çocuk Kitapları > Okul Öncesi > Masal': 'cocuk-genclik',
  'Çocuk Kitapları > Roman': 'roman',
  'Çocuk Kitapları > Çizgi Roman': 'cizgi-roman',
  'Çocuk Kitapları > Şiir': 'siir-drama',
  'İslam > Siyer': 'din-maneviyat',
  'İslam > Tasavvuf': 'din-maneviyat',
}

// Üst-seviye önek eşlemesi — yukarıdaki tabloda olmayan (veri seti ileride
// güncellenirse ortaya çıkabilecek) yeni bir ham kategoriye rastlanırsa,
// en azından " > "dan önceki kısma bakarak makul bir üst kategoriye
// düşsün diye bir yedek. Tabloda karşılığı olan her şey zaten yukarıda
// çözülüyor, bu sadece güvenlik ağı.
const ONEK_YEDEK = {
  Edebiyat: 'diger',
  Tarih: 'tarih',
  Siyaset: 'toplum-siyaset',
  Kültür: 'kultur-sanat',
  Sanat: 'kultur-sanat',
  Din: 'din-maneviyat',
  İslam: 'din-maneviyat',
  Psikoloji: 'psikoloji-felsefe',
  'Felsefe-Düşünce': 'psikoloji-felsefe',
  Eğitim: 'dil-egitim',
  'Diğer Dildeki Yayınlar': 'dil-egitim',
  'Çocuk Kitapları': 'cocuk-genclik',
  'Sinema-Tiyatro': 'siir-drama',
  'Eğlence-Mizah': 'mizah-soylesi',
}

export function hamKategoridenUstKategoriGetir(hamKategori) {
  if (!hamKategori) return 'diger'
  if (HAM_KATEGORI_ESLESTIRME[hamKategori]) return HAM_KATEGORI_ESLESTIRME[hamKategori]
  const onek = hamKategori.split('>')[0].trim()
  return ONEK_YEDEK[onek] || 'diger'
}
